# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Decompress 2016"
email: "team@decompress.com.au"
sponsors_email: "team@decompress.com.au"
description: "Decompress is a community day for designers and developers run by the CSSConf and JSConf team. Our focus is squarely set on creating an all-inclusive space for attendees to learn, share and create. Topics covered are a blend of CSSConf and JSConf, and will even feature some of the same speakers."
baseurl: ""
url: ""
ticket_url: "http://ti.to/cssconf-au/2016/"
jsconf_url: "http://2016.jsconfau.com"
cssconf_url: "http://2016.cssconf.com.au"
decompress_url: "http://decompress.com.au"
collections:
  interviews:
    output: true
    permalink: /interviews/:path/
  team:
    output: false
  speakers:
    output: false



# Build settings
markdown: kramdown
exclude: [vendor]
